spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jorub
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 080525
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create